# Generated by Django 3.0.2 on 2020-02-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingmessage',
            options={'ordering': ['-start_date', 'end_date']},
        ),
    ]
