# Generated by Django 3.0.2 on 2020-02-15 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_userdefaultmanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDefaultManager',
            new_name='UserDefaultAddress',
        ),
    ]
