# Generated by Django 3.0.2 on 2020-02-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200216_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='products.Category'),
        ),
    ]
