# Generated by Django 3.0.2 on 2020-02-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200217_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_defaults',
            field=models.BooleanField(default=False),
        ),
    ]
